name: Build C++ DLL

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Elle tetiklemek için

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repo Kodlarını Çek
      uses: actions/checkout@v4

    - name: MSBuild Yolunu Ayarla
      uses: microsoft/setup-msbuild@v2

    - name: Projeyi Release/x64 Olarak Derle
      run: msbuild /p:Configuration=Release /p:Platform=x64

    - name: Üretilen DLL Dosyasını Yükle (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-DLL
        path: '**/*.dll' # Proje içindeki tüm .dll çıktılarını yakalar
